/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as RecentRouteRouteImport } from './routes/recent.route'
import { Route as ProfileRouteRouteImport } from './routes/profile.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisIdRouteRouteImport } from './routes/analysis.$id.route'

const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRouteRoute = RecentRouteRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRouteRoute = AnalysisIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRoute
  '/recent': typeof RecentRouteRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRoute
  '/recent': typeof RecentRouteRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRoute
  '/recent': typeof RecentRouteRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/recent' | '/analysis' | '/analysis/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/recent' | '/analysis' | '/analysis/$id'
  id: '__root__' | '/' | '/profile' | '/recent' | '/analysis' | '/analysis/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRouteRoute: typeof ProfileRouteRoute
  RecentRouteRoute: typeof RecentRouteRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteRouteImport
      parentRoute: typeof AnalysisRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisIdRouteRoute: typeof AnalysisIdRouteRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisIdRouteRoute: AnalysisIdRouteRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRouteRoute: ProfileRouteRoute,
  RecentRouteRoute: RecentRouteRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
